#!/usr/bin/env bash
set -euo pipefail

GITHUB_REF="${GITHUB_REF:-}"
GITHUB_WORKSPACE="${GITHUB_WORKSPACE:-/github/workspace}"

if ! echo "$GITHUB_REF" | grep -E "^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+"; then
    echo "'$GITHUB_REF' does not refer to a valid tag"
    exit 1
fi

if ! test -d "$GITHUB_WORKSPACE"; then
    echo "$GITHUB_WORKSPACE is missing"
    exit 1
fi

VERSION=$(echo "$GITHUB_REF" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')

# get latest goreleaser release
echo "🌲 Downloading goreleaser"

GORELEASER_DEB=$(curl -s -L https://api.github.com/repos/goreleaser/goreleaser/releases/latest \
    | grep browser_download_url \
    | grep amd64.deb \
    | cut -d '"' -f 4)

curl -s -L -o goreleaser.deb "$GORELEASER_DEB"

echo "🌲 Installing goreleaser"
dpkg -i goreleaser.deb

echo "🌲 Releasing $VERSION"
cd "$GITHUB_WORKSPACE" || exit 1
goreleaser --release-notes CHANGES.md
