#!/usr/bin/env bash
set -euo pipefail

GITHUB_WORKSPACE="${GITHUB_WORKSPACE:-/github/workspace}"

if ! test -d "$GITHUB_WORKSPACE"; then
    echo "$GITHUB_WORKSPACE is missing"
    exit 1
fi

cd "$GITHUB_WORKSPACE" || exit 1
git config --global --add safe.directory "$GITHUB_WORKSPACE"

echo "🌲 Downloading dependencies"
go mod download

# install go get outside our repository to ignore the mod file
pushd /
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
popd

echo "🌲 Running unit tests"
go test ./...
echo ""

echo "🌲 Running golangci-lint"
golangci-lint run

echo "🌲 Testing version"
go run roots.go version
echo ""

echo "🌲 Testing Docker Hub pull with race detection"
go run -race roots.go pull debian /tmp/debian
echo ""

echo "🌲 Testing GCR pull"
go run roots.go pull gcr.io/google-containers/etcd:3.3.10 /tmp/etcd
echo ""

echo "🌲 Testing GHCR pull"
go run roots.go pull ghcr.io/github/issue_metrics:latest /tmp/issue_metrics
echo ""

echo "🌲 Testing Cache Purge"
go run roots.go purge
